function D_ay = lstm1_getContinuousD_ay(c_alpha_fl,c_alpha_fr,c_alpha_rl,c_alpha_rr,m)
%LSTM1_GETCONTINUOUSD_AY
%    D_AY = LSTM1_GETCONTINUOUSD_AY(C_ALPHA_FL,C_ALPHA_FR,C_ALPHA_RL,C_ALPHA_RR,M)

%    This function was generated by the Symbolic Math Toolbox version 8.1.
%    27-Aug-2018 16:16:25

% 
% Linear Single Track Model lstm1
% 
% STATES
% x=[psi_dot;beta] (yaw rate and side slip angle)
% INPUTS
% u=[delta_f;delta_r;M_z] (wheel steering angles, additional yaw moment)
% OUTPUTS
% psi_dot, beta, ay --> use C_psi_dot D_psi_dot, C_beta D_beta, C_ay D_ay
% INFORMATION on parameters
% the cornering stiffness parameters are "tire-wise" so there is no confusion weather it has to be multiplied by 2 or not
% 
% x_dot = A*x + B*u
% y     = C*x + D*u
% 
% Single Track Modell with
% - front steering
% - rear steering
% - cog on road height
% - small angle approximation
% - constant v
% - x = [psi_dot; beta]
% 
t2 = 1.0./m;
D_ay = [t2.*(c_alpha_fl+c_alpha_fr),t2.*(c_alpha_rl+c_alpha_rr),0.0];
