function C_psi_dot = lstm1_getContinuousC_psi_dot
%LSTM1_GETCONTINUOUSC_PSI_DOT
%    C_PSI_DOT = LSTM1_GETCONTINUOUSC_PSI_DOT

%    This function was generated by the Symbolic Math Toolbox version 8.1.
%    27-Aug-2018 16:16:25

% 
% Linear Single Track Model lstm1
% 
% STATES
% x=[psi_dot;beta] (yaw rate and side slip angle)
% INPUTS
% u=[delta_f;delta_r;M_z] (wheel steering angles, additional yaw moment)
% OUTPUTS
% psi_dot, beta, ay --> use C_psi_dot D_psi_dot, C_beta D_beta, C_ay D_ay
% INFORMATION on parameters
% the cornering stiffness parameters are "tire-wise" so there is no confusion weather it has to be multiplied by 2 or not
% 
% x_dot = A*x + B*u
% y     = C*x + D*u
% 
% Single Track Modell with
% - front steering
% - rear steering
% - cog on road height
% - small angle approximation
% - constant v
% - x = [psi_dot; beta]
% 
C_psi_dot = [1.0,0.0];
